# Project: Project_z_podzial
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o Heap.o rpq.o schrage.o
LINKOBJ  = main.o Heap.o rpq.o schrage.o
LIBS     = -L"G:/Programy/Dev_c/Dev-Cpp/MinGW64/lib" -L"G:/Programy/Dev_c/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"G:/Programy/Dev_c/Dev-Cpp/MinGW64/include" -I"G:/Programy/Dev_c/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"G:/Programy/Dev_c/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"G:/Programy/Dev_c/Dev-Cpp/MinGW64/include" -I"G:/Programy/Dev_c/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"G:/Programy/Dev_c/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"G:/Programy/Dev_c/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Project_z_podzial.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

Heap.o: Heap.cpp
	$(CPP) -c Heap.cpp -o Heap.o $(CXXFLAGS)

rpq.o: rpq.cpp
	$(CPP) -c rpq.cpp -o rpq.o $(CXXFLAGS)

schrage.o: schrage.cpp
	$(CPP) -c schrage.cpp -o schrage.o $(CXXFLAGS)
